### ISSUE TITLE
can not change FlutterSlider width

### ISSUE THREAD

**Issue by Ahmedtaha123** [Ali-Azmoud/flutter_xlider#33] opened 2019-10-23 11:17 UTC
if i wrap FlutterSlider with Container and give Container width FlutterSlider  not change 
any help

**Comment by Ali-Azmoud** [comment] 2019-11-27 08:51
Hi
Can you share your code so that I can reproduce it? thanks

**Comment by Ali-Azmoud** [comment] 2019-12-17 12:31
Since you haven't answered this reply for a long time, I'm going to close this issue. Feel free to reopen it if you need to

**Closed by Ali-Azmoud** 2019-12-17 12:31 UTC

**Comment by lvlasuod** [comment] 2020-01-03 10:44
Hey thanks for your useful plugin, but I have the same problem with this plugin I want to increase the width of the trackbar, how can I approach?
