### ISSUE TITLE
Unable to drag to last value

### ISSUE THREAD

**Issue by davidBarbieri** [Ali-Azmoud/flutter_xlider#36] opened 2019-11-17 09:38 UTC
Hi, thanks for this amazing plugin!

I skimmed through the open issues but i didn't figure out a way to fix this. 
The problem is that it''s very tricky to be able to select the last value of a set, this is a gif of my case:

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/39115980/69005698-0ecdd880-0926-11ea-8844-aab79617a3ba.gif)

It doesn't matter if i'm starting the drag from 1, or if its already locked at 9 and i try lo scroll further.
The first value is always correctly reachable.

Thanks a lot again!

**Comment by Ali-Azmoud** [comment] 2019-11-27 08:42
Hi, sorry for my delayed reply.
could you please share your code so that I can reproduce it.

**Comment by davidBarbieri** [comment] 2019-11-29 11:54
Hi aly, sorry for the last response! I commented my custom code as i saw i get the same problem with the default plugin layout:

```
return Padding(
      padding: EdgeInsets.symmetric(horizontal: 20.0),
      child: FlutterSlider(
        values: [_ratingMaxValue / 2],
        max: _ratingMaxValue,
        min: 1,
        /*tooltip: tooltip,
        trackBar: trackBar,
        handler: handler,*/
        handlerHeight: 50.0,
        handlerWidth: 50.0,
        onDragging: (handlerIndex, lowerValue, upperValue) {
          setState(() {
            //print(lowerValue);
            _rating = (0.0 + lowerValue).ceil();
          });
        },
      ),
    );
```

My values go from 1 to 10, and the default value is 5. Most of the times it impossible to drag all the way to 10.

My momentary fix will be to set max value to 11 and do a math.max with 10 so always be able to get to 10

**Comment by Ali-Azmoud** [comment] 2019-12-01 08:49
I'm not sure but I think it's logical. if you grab your handler from very right and try to slide to the right side, you can't reach to the end of slider itself. because your finger reaches to the edge of your phone ... 
I think if you give some padding to both sides of your slider, you should not face this problem anymore.

again I am not sure, I'm going to test it tonight ( my local time ) and let you know

**Comment by Ali-Azmoud** [comment] 2019-12-01 08:52
There is a similar issue [here](https://github.com/Ali-Azmoud/flutter_xlider/issues/8) also

**Comment by davidBarbieri** [comment] 2019-12-01 10:58
Hi Ali, thanks for the hint, i tried playing around with paddings and touchSizes but many times i still struggled to get to 10.

In the example touchSize is set to 50, which is the same size as the handler, and it didn't change much from the behaviour with the default value of 15.

I also tried to change the outmost Padding from 20 to 50, bust still no changes.

This is a gif with the inspector on, so you can see better the situation:
![ezgif com-video-to-gif(1)](https://user-images.githubusercontent.com/39115980/69912641-64c57480-142c-11ea-8285-c80387a8e96c.gif)

I'm not really sure as to why it's only about the upper value and not the lower one. this is a schema of the area value relationship i was expecting:

![slider](https://user-images.githubusercontent.com/39115980/69912952-575eb900-1431-11ea-8826-e3e931f06e50.png)


Without hatchmark the "1" segment works as intended, but looks like the last segment is not working in the same way, kind of crossing with the hatchmark behaviour.
Maybe it's a miscalculation of the segments lenght/start-offsetes?

Hope it helped and didn't confuse you more :D.

Thanks again for this great plugin!

**Comment by Ali-Azmoud** [comment] 2019-12-01 23:02
> Hi Ali, sorry for the late response! I commented my custom code as i saw i get the same problem with the default plugin layout:
> 
> ```
> return Padding(
>       padding: EdgeInsets.symmetric(horizontal: 20.0),
>       child: FlutterSlider(
>         values: [_ratingMaxValue / 2],
>         max: _ratingMaxValue,
>         min: 1,
>         /*tooltip: tooltip,
>         trackBar: trackBar,
>         handler: handler,*/
>         handlerHeight: 50.0,
>         handlerWidth: 50.0,
>         onDragging: (handlerIndex, lowerValue, upperValue) {
>           setState(() {
>             //print(lowerValue);
>             _rating = (0.0 + lowerValue).ceil();
>           });
>         },
>       ),
>     );
> ```
> 
> My values go from 1 to 10, and the default value is 5. Most of the times it impossible to drag all the way to 10.
> 
> My momentary fix will be to set max value to 11 and do a math.min with 10 so always be able to get to 10

Hi again, the code you shared here works well for me. I may need your handler style to check what is going on here

**Comment by Ali-Azmoud** [comment] 2019-12-03 10:02
Hi again. this bug is fixed. I'm going to upload the new version tonight. thanks for your bug report and feedback

**Comment by Ali-Azmoud** [comment] 2019-12-03 22:35
Hey, this bug is fixed in the latest version. I'm going to close this issue, feel free to reopen it if you think problem still exists.

**Closed by Ali-Azmoud** 2019-12-03 22:35 UTC
